import { type Module, inject } from 'langium';
import { createDefaultModule, createDefaultSharedModule, type DefaultSharedModuleContext, type LangiumServices, type LangiumSharedServices, type PartialLangiumServices } from 'langium/lsp';
import { SellhubLiquidGeneratedModule, SellhubLiquidGeneratedSharedModule } from './generated/module.ts';
import { SellhubLiquidValidator, registerValidationChecks } from './sellhub-liquid-validator.js';

/**
 * Declaration of custom services - add your own service classes here.
 */
export type SellhubLiquidAddedServices = {
    validation: {
        SellhubLiquidValidator: SellhubLiquidValidator
    }
}

/**
 * Union of Langium default services and your custom services - use this as constructor parameter
 * of custom service classes.
 */
export type SellhubLiquidServices = LangiumServices & SellhubLiquidAddedServices

/**
 * Dependency injection module that overrides Langium default services and contributes the
 * declared custom services. The Langium defaults can be partially specified to override only
 * selected services, while the custom services must be fully specified.
 */
export const SellhubLiquidModule: Module<SellhubLiquidServices, PartialLangiumServices & SellhubLiquidAddedServices> = {
    validation: {
        SellhubLiquidValidator: () => new SellhubLiquidValidator()
    }
};

/**
 * Create the full set of services required by Langium.
 *
 * First inject the shared services by merging two modules:
 *  - Langium default shared services
 *  - Services generated by langium-cli
 *
 * Then inject the language-specific services by merging three modules:
 *  - Langium default language-specific services
 *  - Services generated by langium-cli
 *  - Services specified in this file
 *
 * @param context Optional module context with the LSP connection
 * @returns An object wrapping the shared services and the language-specific services
 */
export function createSellhubLiquidServices(context: DefaultSharedModuleContext): {
    shared: LangiumSharedServices,
    SellhubLiquid: SellhubLiquidServices
} {
    const shared = inject(
        createDefaultSharedModule(context),
        SellhubLiquidGeneratedSharedModule
    );
    const SellhubLiquid = inject(
        createDefaultModule({ shared }),
        SellhubLiquidGeneratedModule,
        SellhubLiquidModule
    );
    shared.ServiceRegistry.register(SellhubLiquid);
    registerValidationChecks(SellhubLiquid);
    if (!context.connection) {
        // We don't run inside a language server
        // Therefore, initialize the configuration provider instantly
        shared.workspace.ConfigurationProvider.initialized({});
    }
    return { shared, SellhubLiquid };
}
import { type Module, inject } from 'langium';
import {
    createDefaultModule,
    createDefaultSharedModule,
    type DefaultSharedModuleContext,
    type LangiumServices,
    type LangiumSharedServices,
    type PartialLangiumServices
} from 'langium/lsp';
import { SellhubLiquidGeneratedModule, SellhubLiquidGeneratedSharedModule } from './generated/module.js';
import { SellhubLiquidValidator, registerValidationChecks } from './sellhub-liquid-validator.js';
import { R2Client } from './services/r2-client.js';
import { ConfigService } from './services/config-service.js';
import { IslandsCompletionProvider } from './providers/islands-completion-provider.js';
import { ContextCompletionProvider } from './providers/context-completion-provider.js';
import { IslandsHoverProvider } from './providers/islands-hover-provider.js';

/**
 * Declaration of custom services - add your own service classes here.
 */
export type SellhubLiquidAddedServices = {
    validation: {
        SellhubLiquidValidator: SellhubLiquidValidator
    },
    services: {
        R2Client: R2Client,
        ConfigService: ConfigService
    },
    providers: {
        IslandsCompletionProvider: IslandsCompletionProvider,
        ContextCompletionProvider: ContextCompletionProvider,
        IslandsHoverProvider: IslandsHoverProvider
    }
}

/**
 * Union of Langium default services and your custom services - use this as constructor parameter
 * of custom service classes.
 */
export type SellhubLiquidServices = LangiumServices & SellhubLiquidAddedServices

/**
 * Dependency injection module that overrides Langium default services and contributes the
 * declared custom services. The Langium defaults can be partially specified to override only
 * selected services, while the custom services must be fully specified.
 */
export const SellhubLiquidModule: Module<SellhubLiquidServices, PartialLangiumServices & SellhubLiquidAddedServices> = {
    services: {
        ConfigService: (services) => {
            const configService = new ConfigService();
            // Set configuration provider from shared services
            if (services.shared && services.shared.workspace && services.shared.workspace.ConfigurationProvider) {
                configService.setConfigurationProvider(services.shared.workspace.ConfigurationProvider);
            }
            return configService;
        },
        R2Client: (services) => {
            // Initialize R2Client with configuration from ConfigService
            const configService = services.services.ConfigService;
            const config = configService.getConfig();
            return new R2Client(config);
        }
    },
    providers: {
        IslandsCompletionProvider: (services) => {
            const r2Client = services.services.R2Client;
            return new IslandsCompletionProvider(services, r2Client);
        },
        ContextCompletionProvider: () => new ContextCompletionProvider(),
        IslandsHoverProvider: (services) => {
            const r2Client = services.services.R2Client;
            return new IslandsHoverProvider(r2Client);
        }
    },
    validation: {
        SellhubLiquidValidator: (services) => {
            const r2Client = services.services.R2Client;
            return new SellhubLiquidValidator(r2Client);
        }
    },
    lsp: {
        CompletionProvider: (services) => services.providers.IslandsCompletionProvider
    }
};

/**
 * Create the full set of services required by Langium.
 *
 * First inject the shared services by merging two modules:
 *  - Langium default shared services
 *  - Services generated by langium-cli
 *
 * Then inject the language-specific services by merging three modules:
 *  - Langium default language-specific services
 *  - Services generated by langium-cli
 *  - Services specified in this file
 *
 * @param context Optional module context with the LSP connection
 * @returns An object wrapping the shared services and the language-specific services
 */
export function createSellhubLiquidServices(context: DefaultSharedModuleContext): {
    shared: LangiumSharedServices,
    SellhubLiquid: SellhubLiquidServices
} {
    const shared = inject(
        createDefaultSharedModule(context),
        SellhubLiquidGeneratedSharedModule
    );
    const SellhubLiquid = inject(
        createDefaultModule({ shared }),
        SellhubLiquidGeneratedModule,
        SellhubLiquidModule
    );
    shared.ServiceRegistry.register(SellhubLiquid);

    // Load configuration asynchronously
    if (context.connection) {
        // Running in language server, wait for initialization
        context.connection.onInitialized(async () => {
            await SellhubLiquid.services.ConfigService.loadConfiguration();
            // Update R2Client with loaded configuration
            const config = SellhubLiquid.services.ConfigService.getConfig();
            SellhubLiquid.services.R2Client.updateConfig(config);
        });
    } else {
        // Not running in language server, initialize immediately
        shared.workspace.ConfigurationProvider.initialized({});
    }

    registerValidationChecks(SellhubLiquid);

    return { shared, SellhubLiquid };
}